# Generated by Django 3.2.24 on 2024-02-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('a', 'Admin'), ('s', 'Student'), ('t', 'Teacher'), ('p', 'Parent')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
