# Generated by Django 3.2.24 on 2024-02-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisiteSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='academic_info.subject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='academic_info.subject')),
            ],
            options={
                'unique_together': {('subject', 'prerequisite_subject')},
            },
        ),
        migrations.CreateModel(
            name='Branch_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_info.branch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_info.subject')),
            ],
            options={
                'unique_together': {('branch', 'subject')},
            },
        ),
    ]
