# Generated by Django 3.2.24 on 2024-02-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_subject',
            name='semester',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
