# Generated by Django 3.2.24 on 2024-02-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('material', models.FileField(upload_to='materials/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_info.subject')),
            ],
        ),
    ]
