# Generated by Django 3.2.24 on 2024-02-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('p', 'Paper'), ('n', 'Notes')], default=200, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='year',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
