# Generated by Django 3.2.24 on 2024-02-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0002_auto_20240226_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='aproved',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
