# Generated by Django 3.2.24 on 2024-02-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0003_material_aproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='aproved',
            field=models.BooleanField(default=False),
        ),
    ]
