# Generated by Django 3.2.24 on 2024-02-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0004_alter_material_aproved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='semester',
        ),
    ]
